services:
  - type: web
    name: super-sonic-prototypes
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_KEYSTATIC_GITHUB_REPO_OWNER
        sync: false
      - key: VITE_KEYSTATIC_GITHUB_REPO_NAME
        sync: false


